title: 어디에나 있는 개발자
author: 어디에나 있는 개발자
subtitle: The life of a frustrated engineer

url: "https://JIWONPARK1.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://JIWONPARK1.github.io"
footer_text: "어디에나 있는 개발자"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: "About"
    link: "about"
  - name: "tags"
    link: "/tags"
  # - name: "Resume"
  #   absolute-link: "https://JIWONPARK1.github.io/"
