permalink: /:year:month:day/:title
url: https://jiwonpark1.github.io/
baseurl: /

# variables
name: 구식 개발자
description: 안녕하세요 . 옛스런 구식 개발자입니다.
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
